# Generated by Django 5.2 on 2025-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
